<?xml version="1.0"?>
<robot name="f120a" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find megarover_description)/urdf/f120a_base_model.xacro" />
  <xacro:include filename="$(find megarover_description)/urdf/f120a.gazebo" />
  <!-- OPTION: LRF TG30 -->
  <!-- <xacro:include filename="$(find vs_rover_options_description)/urdf/lrf/tg30_f120a.xacro" /> -->
  <!-- OPTION: bumper sensor -->
  <!-- <xacro:include filename="$(find vs_rover_options_description)/urdf/bumper/bumper_f120a.xacro" />
  <xacro:bumperbaseboard prefix="front" parent="base_link" xyz="0 ${0.272 + bumper_alu_frame_y_offset} 0.0385" z_dir="180" />
  <xacro:bumperbaseboard prefix="back" parent="base_link" xyz="0 ${-0.272 + bumper_alu_frame_y_offset} 0.0385" z_dir="0" /> -->
  <!-- OPTION: camera stay -->
  <xacro:include filename="$(find vs_rover_options_description)/urdf/cam_stay/cam_stay_f120a.xacro" />
  <!-- OPTION: Intel Realsense depth camera D435i (camera stay is required)  -->
  <xacro:include filename="$(find vs_rover_options_description)/urdf/depth_cam/_d435i.urdf.xacro" />
  <xacro:sensor_d435i parent="cam_mount_link" use_nominal_extrinsics="true">
    <origin xyz="0.0295 0 0.0095" rpy="0 0 0" />
  </xacro:sensor_d435i>
  <!-- OPTION: AMIR 740 (disabled by default because of interference with camera stay)-->
  <!-- <xacro:include filename="$(find amir_description)/urdf/amir_for_rover.xacro" />
  <joint name="base_fixed" type="fixed">
    <origin xyz="0.0 0.0 0.4365" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="link0_1" />
  </joint> -->
</robot>